from typing import Sequence, Union
import sqlalchemy as sa
from alembic import op
revision: str = 'sprint4_b1c2d3e4f5a6'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.execute(sa.text("ALTER TYPE projects_status_enum ADD VALUE IF NOT EXISTS 'close'"))
    op.execute(sa.text("ALTER TYPE projects_status_enum ADD VALUE IF NOT EXISTS 'deleted'"))
    op.execute(sa.text("\n            DO $m$\n            BEGIN\n                IF NOT EXISTS (\n                    SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace\n                    WHERE t.typname = 'application_status_enum' AND n.nspname = 'public'\n                ) THEN\n                    CREATE TYPE public.application_status_enum AS ENUM (\n                        'pending', 'accepted', 'rejected', 'cancelled'\n                    );\n                END IF;\n\n                IF NOT EXISTS (\n                    SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace\n                    WHERE t.typname = 'cancel_reason_enum' AND n.nspname = 'public'\n                ) THEN\n                    CREATE TYPE public.cancel_reason_enum AS ENUM (\n                        'user_withdrawn', 'user_left', 'removed_by_owner',\n                        'resume_updated', 'another_accepted',\n                        'project_paused', 'project_deleted', 'project_closed'\n                    );\n                END IF;\n\n                IF NOT EXISTS (\n                    SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace\n                    WHERE t.typname = 'notification_event_enum' AND n.nspname = 'public'\n                ) THEN\n                    CREATE TYPE public.notification_event_enum AS ENUM (\n                        'application_received', 'application_accepted',\n                        'application_rejected', 'application_cancelled'\n                    );\n                END IF;\n            END\n            $m$;\n            "))
    op.execute(sa.text("\n            DO $r$\n            BEGIN\n                IF EXISTS (\n                    SELECT 1 FROM information_schema.columns\n                    WHERE table_schema = 'public' AND table_name = 'project_vacancies'\n                      AND column_name = 'employment'\n                ) THEN\n                    ALTER TABLE public.project_vacancies\n                    RENAME COLUMN employment TO commitment_level;\n                END IF;\n            END\n            $r$;\n            "))
    op.execute(sa.text("\n            DO $p$\n            BEGIN\n                IF NOT EXISTS (\n                    SELECT 1 FROM information_schema.columns\n                    WHERE table_schema = 'public' AND table_name = 'projects'\n                      AND column_name = 'last_seen_applications_at'\n                ) THEN\n                    ALTER TABLE public.projects\n                    ADD COLUMN last_seen_applications_at TIMESTAMPTZ;\n                END IF;\n\n                IF NOT EXISTS (\n                    SELECT 1 FROM information_schema.columns\n                    WHERE table_schema = 'public' AND table_name = 'projects'\n                      AND column_name = 'close_member_ids'\n                ) THEN\n                    ALTER TABLE public.projects\n                    ADD COLUMN close_member_ids JSONB;\n                END IF;\n            END\n            $p$;\n            "))
    op.execute(sa.text("\n            DO $res$\n            BEGIN\n                IF NOT EXISTS (\n                    SELECT 1 FROM information_schema.columns\n                    WHERE table_schema = 'public' AND table_name = 'resumes'\n                      AND column_name = 'work_format'\n                ) THEN\n                    ALTER TABLE public.resumes\n                    ADD COLUMN work_format public.work_format_enum;\n                END IF;\n\n                IF NOT EXISTS (\n                    SELECT 1 FROM information_schema.columns\n                    WHERE table_schema = 'public' AND table_name = 'resumes'\n                      AND column_name = 'schedule'\n                ) THEN\n                    ALTER TABLE public.resumes\n                    ADD COLUMN schedule public.schedule_enum;\n                END IF;\n\n                IF NOT EXISTS (\n                    SELECT 1 FROM information_schema.columns\n                    WHERE table_schema = 'public' AND table_name = 'resumes'\n                      AND column_name = 'salary_type'\n                ) THEN\n                    ALTER TABLE public.resumes\n                    ADD COLUMN salary_type public.salary_type_enum;\n                END IF;\n\n                IF NOT EXISTS (\n                    SELECT 1 FROM information_schema.columns\n                    WHERE table_schema = 'public' AND table_name = 'resumes'\n                      AND column_name = 'contract_type'\n                ) THEN\n                    ALTER TABLE public.resumes\n                    ADD COLUMN contract_type public.contract_type_enum;\n                END IF;\n\n                IF NOT EXISTS (\n                    SELECT 1 FROM information_schema.columns\n                    WHERE table_schema = 'public' AND table_name = 'resumes'\n                      AND column_name = 'computed_experience_level'\n                ) THEN\n                    ALTER TABLE public.resumes\n                    ADD COLUMN computed_experience_level public.projects_vacancies_enum;\n                END IF;\n            END\n            $res$;\n            "))
    op.execute(sa.text("\n            CREATE TABLE IF NOT EXISTS public.applications (\n                id              SERIAL PRIMARY KEY,\n                resume_id       INTEGER NOT NULL REFERENCES public.resumes(id) ON DELETE CASCADE,\n                vacancy_id      INTEGER NOT NULL REFERENCES public.project_vacancies(id) ON DELETE CASCADE,\n                status          public.application_status_enum NOT NULL DEFAULT 'pending',\n                cancel_reason   public.cancel_reason_enum,\n                created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n                updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()\n            )\n            "))
    op.execute(sa.text('\n            ALTER TABLE public.applications\n                DROP CONSTRAINT IF EXISTS uq_application_resume_vacancy\n            '))
    op.execute(sa.text("\n            CREATE UNIQUE INDEX IF NOT EXISTS uq_active_application_resume_vacancy\n                ON public.applications (resume_id, vacancy_id)\n                WHERE status IN ('pending', 'accepted')\n            "))
    op.execute(sa.text('\n            CREATE TABLE IF NOT EXISTS public.vacancy_assignments (\n                id              SERIAL PRIMARY KEY,\n                resume_id       INTEGER NOT NULL REFERENCES public.resumes(id) ON DELETE CASCADE,\n                vacancy_id      INTEGER NOT NULL REFERENCES public.project_vacancies(id) ON DELETE CASCADE,\n                application_id  INTEGER NOT NULL REFERENCES public.applications(id) ON DELETE CASCADE,\n                created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n                released_at     TIMESTAMPTZ\n            )\n            '))
    op.execute(sa.text('\n            CREATE UNIQUE INDEX IF NOT EXISTS uq_active_vacancy_assignment\n                ON public.vacancy_assignments (vacancy_id)\n                WHERE released_at IS NULL\n            '))
    op.execute(sa.text('\n            CREATE UNIQUE INDEX IF NOT EXISTS uq_active_resume_assignment\n                ON public.vacancy_assignments (resume_id)\n                WHERE released_at IS NULL\n            '))
    op.execute(sa.text("\n            CREATE TABLE IF NOT EXISTS public.notifications (\n                id              SERIAL PRIMARY KEY,\n                user_id         INTEGER NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,\n                event           public.notification_event_enum NOT NULL,\n                application_id  INTEGER REFERENCES public.applications(id) ON DELETE SET NULL,\n                project_id      INTEGER REFERENCES public.projects(id) ON DELETE SET NULL,\n                payload         JSONB NOT NULL DEFAULT '{}',\n                is_read         BOOLEAN NOT NULL DEFAULT FALSE,\n                created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()\n            )\n            "))
    op.execute(sa.text('\n            CREATE INDEX IF NOT EXISTS idx_notifications_user_unread\n                ON public.notifications (user_id, is_read)\n                WHERE is_read = FALSE\n            '))

def downgrade() -> None:
    op.execute(sa.text('DROP TABLE IF EXISTS public.notifications'))
    op.execute(sa.text('DROP TABLE IF EXISTS public.vacancy_assignments'))
    op.execute(sa.text('DROP TABLE IF EXISTS public.applications'))
    op.execute(sa.text('\n            ALTER TABLE public.resumes\n                DROP COLUMN IF EXISTS work_format,\n                DROP COLUMN IF EXISTS schedule,\n                DROP COLUMN IF EXISTS salary_type,\n                DROP COLUMN IF EXISTS contract_type,\n                DROP COLUMN IF EXISTS computed_experience_level\n            '))
    op.execute(sa.text('\n            ALTER TABLE public.projects\n                DROP COLUMN IF EXISTS last_seen_applications_at,\n                DROP COLUMN IF EXISTS close_member_ids\n            '))
    op.execute(sa.text("\n            DO $r$\n            BEGIN\n                IF EXISTS (\n                    SELECT 1 FROM information_schema.columns\n                    WHERE table_schema = 'public' AND table_name = 'project_vacancies'\n                      AND column_name = 'commitment_level'\n                ) THEN\n                    ALTER TABLE public.project_vacancies\n                    RENAME COLUMN commitment_level TO employment;\n                END IF;\n            END\n            $r$;\n            "))
    op.execute(sa.text('DROP TYPE IF EXISTS public.notification_event_enum'))
    op.execute(sa.text('DROP TYPE IF EXISTS public.cancel_reason_enum'))
    op.execute(sa.text('DROP TYPE IF EXISTS public.application_status_enum'))
