"""constraints

Revision ID: 3b4d6e6f4a2c
Revises: 1b267146fdcd
Create Date: 2026-04-12 04:04:05.985644

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3b4d6e6f4a2c"
down_revision: Union[str, Sequence[str], None] = "1b267146fdcd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "cities", ["title"])
    op.create_unique_constraint(None, "profiles", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "profiles", type_="unique")
    op.drop_constraint(None, "cities", type_="unique")
    # ### end Alembic commands ###
