EMBEDDING_DIMENSION = 384
EMBEDDING_MODEL_VERSION = 'multilingual-e5-small@v4'
EMBEDDING_MODEL_NAME = 'intfloat/multilingual-e5-small'
EMBEDDING_PASSAGE_PREFIX = 'passage: '
EMBEDDING_QUERY_PREFIX = 'query: '
