HYBRID_WEIGHT_EMBEDDING = 0.45
HYBRID_WEIGHT_ROLE = 0.30
HYBRID_WEIGHT_SKILLS = 0.25

EMBEDDING_SIM_FLOOR = 0.65
EMBEDDING_SIM_CEIL = 0.90

RECOMMENDATION_CANDIDATE_MULTIPLIER = 10
RECOMMENDATION_CANDIDATE_MAX = 200
